[package]
name = "icy_term"
version = "0.1.3"
edition = "2021"
description = "A terminal program supporting CP437 and PetScii"

[package.metadata.bundle]
name = "Icy Term"
identifier = "com.github.icy_term"
icon = [ "assets/128x128@2x.png" ]
resources = []
copyright = "Copyright (c) Mike Krüger 2022. All rights reserved."

[dependencies]
iced = { path = "../iced", features = ["canvas", "image", "tokio", "debug"] }
iced_native = { path = "../iced/native" }
icy_engine = { path = "../icy_engine" }
directories = "4.0.1"
rfd = "0.10.0"
walkdir = "2"
toml = "0.5.9"
lazy_static = "1.4.0"
open = "3.0.3"
notify = "5.0.0"
gabi = "0.2.6"
clipboard = "0.5.0"
serde = "1.0.147"
serde_derive = "1.0.145"

[profile.release]
strip = "symbols"
