[package]
name = "icy_term"
version = "0.4.0"
edition = "2021"
description = "A terminal program supporting CP437, PetScii and ViewData"

[package.metadata.bundle]
name = "Icy Term"
identifier = "com.github.icy_term"
icon = [ "assets/128x128@2x.png" ]
resources = []
copyright = "Copyright (c) Mike Krüger 2022. All rights reserved."

[dependencies]
eframe = "0.20.1"
egui_extras = { version="0.20.0", features = ["svg"] }
egui_glow = "0.20.1"
glow = "0.11.2"

#sound
cpal = { git = "https://github.com/RustAudio/cpal.git" }
anyhow = "1.0"
icy_engine = { git = "https://github.com/mkrueger/icy_engine.git" }
tokio = { version = "1.21.2", features = ["full"] }

directories = "4.0.1"
rfd = "0.10.0"
walkdir = "2"
toml = "0.5.9"
lazy_static = "1.4.0"
open = "3.0.3"
notify = "5.0.0"
gabi = "0.2.6"
clipboard = "0.5.0"
serde = "1.0.147"
serde_derive = "1.0.145"
async-trait = "0.1.58"
rand = "0.8"
poll-promise = { version = "0.2.0", features = ["tokio"] }

i18n-embed = { version = "0.13.4", features = ["fluent-system", "desktop-requester"]} 
i18n-embed-fl = "0.6.4"
rust-embed = "6.4.2"
once_cell = "1.16.0"
ssh-rs = "0.3.1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tracing-subscriber = "0.3"

# web:
[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.6"
tracing-wasm = "0.2"
wasm-bindgen-futures = "0.4"

[profile.release]
strip = "symbols"
