[package]
name = "icy_term"
version = "0.2.3"
edition = "2021"
description = "A terminal program supporting CP437 and PetScii"

[package.metadata.bundle]
name = "Icy Term"
identifier = "com.github.icy_term"
icon = [ "assets/128x128@2x.png" ]
resources = []
copyright = "Copyright (c) Mike Krüger 2022. All rights reserved."

[dependencies]
iced = {version="0.5.2", features = ["canvas", "image", "svg", "tokio", "debug"] }
iced_native = "0.6.1"
iced_graphics = "0.4.0"
iced_futures = "0.5.1"
iced_aw = { git = "https://github.com/iced-rs/iced_aw", features = ["colors", "card", "modal", "tab_bar"] }
# iced = { path = "../iced", features = ["canvas", "image", "svg", "tokio", "debug"] }
#iced_native = { path = "../iced/native" }
#iced_futures = { path = "../iced/futures", features = ["tokio"] }
#iced_graphics = { path = "../iced/graphics" }

#sound
cpal = { git = "https://github.com/RustAudio/cpal.git" }
anyhow = "1.0"

icy_engine = { path = "../icy_engine" }
tokio = { version = "1.21.2", features = ["full"] }

directories = "4.0.1"
rfd = "0.10.0"
walkdir = "2"
toml = "0.5.9"
lazy_static = "1.4.0"
open = "3.0.3"
notify = "5.0.0"
gabi = "0.2.6"
clipboard = "0.5.0"
serde = "1.0.147"
serde_derive = "1.0.145"
async-trait = "0.1.58"
rand = "0.8"

[profile.release]
strip = "symbols"
