name: Build
on:
  workflow_run:
    workflows: ["Run Tests"]
    branches: [main]
    types: 
      - completed
env:
  CARGO_TERM_COLOR: always
jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install gtk
      run: |
        sudo apt-get update
        sudo apt-get install build-essential libgtk-3-dev libasound2-dev libxcb-shape0-dev libxcb-xfixes0-dev
    - name: Install cargo bundle
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: cargo-bundle
    - name: Build bundle
      uses: actions-rs/cargo@v1
      with:
        command: bundle
        args: --release
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: icy_term_linux
        path: |
          target/release/bundle/deb/game_cheetah_*.deb
          build/file_id.diz

  build_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build bundle
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release
    - name: Install WiX
      run: dotnet tool install --global wix --version 4.0.1

    - name: Get Version
      run: echo "VERSION=$(cat Cargo.toml | grep "version"  | awk -F"\"" '{print $2}' | head -n 1)" >> $GITHUB_ENV
    - name: Crate msi installer
      run: |
        wix extension add WixToolset.UI.wixext WixToolset.Util.wixext
        wix build -arch "x64" -ext WixToolset.UI.wixext -ext WixToolset.Util.wixext \
        -out "./icy_term-$VERSION-installer.msi" "build/windows/icy_term.wxs"
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: icy_term
        path: |
          icy_term-*-installer.msi
          build/file_id.diz
